<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta">

<!-- ===== LOWER TOP ===== -->

<xacro:macro name="parallel" params="parent name length width link_radius link_material">
<joint name="${name}_alpha" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="0 0 0"
    />
    <parent link="${parent}"/>
    <child link="${name}_root"/>
</joint>

<link name="${name}_root">
</link>

<joint name="${name}_L_beta_top" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="0 ${width/2} 0"
    />
    <parent link="${name}_root"/>
    <child link="${name}_L_link"/>
</joint>

<link name="${name}_L_link">
<visual>
    <geometry>
        <cylinder
            length="${length}"
            radius="${link_radius}"
        />
    </geometry>
    <origin
        rpy="0 ${pi/2} 0"
        xyz="${length/2} 0 0"
    />
    <material name="${link_material}"/>
</visual>
<collision>
    <geometry>
        <cylinder
            length="${length}"
            radius="${link_radius}"
        />
    </geometry>
    <origin
        rpy="0 ${pi/2} 0"
        xyz="${length/2} 0 0"
    />
</collision>
</link>

<joint name="${name}_L_beta_bot" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="${length} 0 0"
    />
    <parent link="${name}_L_link"/>
    <child link="${name}_L_link_end"/>
</joint>

<link name="${name}_L_link_end">
</link>

<joint name="${name}_L_gamma" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="0 ${-width/2} 0"
    />
    <parent link="${name}_L_link_end"/>
    <child link="${name}_end"/>
</joint>

<joint name="${name}_R_beta_top" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="0 ${-width/2} 0"
    />
    <parent link="${name}_root"/>
    <child link="${name}_R_link"/>
</joint>

<link name="${name}_R_link">
<visual>
    <geometry>
        <cylinder
            length="${length}"
            radius="${link_radius}"
        />
    </geometry>
    <origin
        rpy="0 ${pi/2} 0"
        xyz="${length/2} 0 0"
    />
    <material name="${link_material}"/>
</visual>
<collision>
    <geometry>
        <cylinder
            length="${length}"
            radius="${link_radius}"
        />
    </geometry>
    <origin
        rpy="0 ${pi/2} 0"
        xyz="${length/2} 0 0"
    />
</collision>
</link>

<joint name="${name}_R_beta_bot" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="${length} 0 0"
    />
    <parent link="${name}_R_link"/>
    <child link="${name}_R_link_end"/>
</joint>

<link name="${name}_R_link_end">
</link>

<gazebo>
<joint name="${name}_R_gamma" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="0 ${width/2} 0"
    />
    <parent link="${name}_R_link_end"/>
    <child link="${name}_end"/>
</joint>
</gazebo>

<link name="${name}_end">
</link>

</xacro:macro>

<xacro:parallel
    parent="lower_1_parent" name="lower_1" length="${lower_length}"
    width="${lower_width}" link_material="lower" link_radius="${lower_radius}"
/>
<xacro:parallel
    parent="lower_2_parent" name="lower_2" length="${lower_length}"
    width="${lower_width}" link_material="lower" link_radius="${lower_radius}"
/>
<xacro:parallel
    parent="lower_3_parent" name="lower_3" length="${lower_length}"
    width="${lower_width}" link_material="lower" link_radius="${lower_radius}"
/>

</robot>
