<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta">

<!-- ===== PSEUDO_ELBOW_OFFSET ===== -->

<xacro:macro name="joint_upper_to_pseudo_elbow_offset" params="number">
<joint name="upper_to_pseudo_elbow_offset_${number}" type="revolute">
    <axis xyz="0 1 0"/>
    <limit
        effort="1000.0"
        lower="${-pi/2}"
        upper="${pi/2}"
        velocity="0.5"
    />
    <origin
        rpy="0 0 ${pi}"
        xyz="${upper_length} 0 0"
    />
    <parent link="upper_${number}"/>
    <child link="pseudo_elbow_offset_${number}"/>
</joint>
</xacro:macro>

<xacro:joint_upper_to_pseudo_elbow_offset number="1"/>
<xacro:joint_upper_to_pseudo_elbow_offset number="2"/>
<xacro:joint_upper_to_pseudo_elbow_offset number="3"/>

<xacro:macro name="link_pseudo_elbow_offset" params="number">
<link name="pseudo_elbow_offset_${number}">
<visual>
    <geometry>
        <cylinder length="${end_effector_radius}" radius="${lower_radius}"/>
    </geometry>
    <origin
        rpy="0 ${pi/2} 0"
        xyz="${end_effector_radius/2} 0 0"
    />
    <material name="virtual_link"/>
</visual>
</link>
</xacro:macro>

<xacro:link_pseudo_elbow_offset number="1"/>
<xacro:link_pseudo_elbow_offset number="2"/>
<xacro:link_pseudo_elbow_offset number="3"/>


<!-- ===== PSEUDO_ELBOW ===== -->

<xacro:macro name="joint_pseudo_elbow_offset_to_pseudo_elbow" params="number">
<joint name="pseudo_elbow_offset_to_pseudo_elbow_${number}" type="revolute">
    <axis xyz="0 1 0"/>
    <limit
        effort="1000.0"
        lower="${-pi/2}"
        upper="${pi/2}"
        velocity="0.5"
    />
    <origin
        rpy="0 0 0"
        xyz="${end_effector_radius} 0 0"
    />
    <parent link="pseudo_elbow_offset_${number}"/>
    <child link="pseudo_elbow_${number}"/>
</joint>
</xacro:macro>

<xacro:joint_pseudo_elbow_offset_to_pseudo_elbow number="1"/>
<xacro:joint_pseudo_elbow_offset_to_pseudo_elbow number="2"/>
<xacro:joint_pseudo_elbow_offset_to_pseudo_elbow number="3"/>

<xacro:macro name="link_pseudo_elbow" params="number">
<link name="pseudo_elbow_${number}">
</link>
</xacro:macro>

<xacro:link_pseudo_elbow number="1"/>
<xacro:link_pseudo_elbow number="2"/>
<xacro:link_pseudo_elbow number="3"/>

<!-- ===== VIRTUAL_LOWER ===== -->

<xacro:macro name="joint_pseudo_elbow_to_virtual_lower" params="number">
<joint name="pseudo_elbow_to_virtual_lower_${number}" type="revolute">
    <axis xyz="0 0 1"/>
    <limit
        effort="1000.0"
        lower="${-pi/2}"
        upper="${pi/2}"
        velocity="0.5"
    />
    <origin
        rpy="0 0 0"
        xyz="0 0 0"
    />
    <parent link="pseudo_elbow_${number}"/>
    <child link="virtual_lower_${number}"/>
</joint>
</xacro:macro>

<xacro:joint_pseudo_elbow_to_virtual_lower number="1"/>
<xacro:joint_pseudo_elbow_to_virtual_lower number="2"/>
<xacro:joint_pseudo_elbow_to_virtual_lower number="3"/>

<xacro:macro name="link_virtual_lower" params="number">
<link name="virtual_lower_${number}">
<visual>
    <geometry>
        <cylinder length="${lower_vertical_length}" radius="${lower_radius}"/>
    </geometry>
    <origin
        rpy="0 ${pi/2} 0"
        xyz="${lower_vertical_length/2} 0 0"
    />
    <material name="virtual_link"/>
</visual>
</link>
</xacro:macro>

<xacro:link_virtual_lower number="1"/>
<xacro:link_virtual_lower number="2"/>
<xacro:link_virtual_lower number="3"/>


<!-- ===== VIRTUAL END EFFECTORS ===== -->

<xacro:macro name="joint_virtual_lower_to_virtual_end_effector" params="number">
<joint name="virtual_lower_to_virtual_end_effector_${number}" type="fixed">
    <origin
        rpy="0 0 0"
        xyz="${lower_vertical_length} 0 0"
    />
    <parent link="virtual_lower_${number}"/>
    <child link="virtual_end_effector_${number}"/>
</joint>
</xacro:macro>

<xacro:joint_virtual_lower_to_virtual_end_effector number="1"/>
<xacro:joint_virtual_lower_to_virtual_end_effector number="2"/>
<xacro:joint_virtual_lower_to_virtual_end_effector number="3"/>

<xacro:macro name="link_virtual_end_effector" params="number">
<link name="virtual_end_effector_${number}">
    <visual>
        <geometry>
            <sphere radius="${break_indicator_radius}"/>
        </geometry>
        <material name="break_indicator"/>
    </visual>
</link>
</xacro:macro>

<xacro:link_virtual_end_effector number="1"/>
<xacro:link_virtual_end_effector number="2"/>
<xacro:link_virtual_end_effector number="3"/>

</robot>
