<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta">


<!-- ===== VIRTUAL END EFFECTORS ===== -->

<!--
<xacro:macro name="link_virtual_end_effector" params="number">
<link name="virtual_end_effector_${number}">
    <visual>
        <geometry>
            <sphere radius="break_indicator_radius"/>
        </geometry>
        <material name="break_indicator"/>
    </visual>
</link>
</xacro:macro>

<xacro:link_virtual_end_effector number="1"/>
<xacro:link_virtual_end_effector number="2"/>
<xacro:link_virtual_end_effector number="3"/>
-->

<!-- ===== ACTUAL END EFFECTOR ===== -->

<joint name="lower_bot_1_to_virtual_end_effector_offset" type="revolute">
    <axis xyz="0 -1 0"/>
    <limit
        effort="1000.0"
        lower="${-pi/2}"
        upper="${pi/2}"
        velocity="0.5"
    />
    <origin
        rpy="0 0 0"
        xyz="0 ${-lower_horizontal_length/2} 0"
    />
    <parent link="lower_bot_1"/>
    <child link="virtual_end_effector_offset"/>
</joint>

<link name="virtual_end_effector_offset">
    <visual>
        <geometry>
            <cylinder
                length="${end_effector_radius}"
                radius="${end_effector_depth}"
            />
        </geometry>
        <origin rpy="0 ${pi/2} 0" xyz="${end_effector_radius/2} 0 0"/>
        <material name="virtual_link"/>
    </visual>
</link>

<joint name="virtual_end_effector_offset_to_end_effector" type="fixed">
    <origin rpy="0 0 0" xyz="${end_effector_radius} 0 0"/>
    <parent link="virtual_end_effector_offset"/>
    <child link="end_effector"/>
</joint>

<link name="end_effector">
    <visual>
        <geometry>
            <cylinder
                length="${end_effector_depth}"
                radius="${end_effector_radius}"
            />
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <material name="physical_link"/>
    </visual>
    <collision>
        <geometry>
            <cylinder
                length="${end_effector_depth}"
                radius="${end_effector_radius}"
            />
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
</link>

</robot>
