<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta_parameters">


<!-- ===== JOINTS ===== -->

<xacro:macro name="joint_theta" params="number yaw">
<joint name="theta_${number}" type="revolute">
    <axis xyz="0 1 0"/>
    <limit
        effort="1000.0"
        lower="${-pi/2}"
        upper="${pi/2}"
        velocity="0.5"
    />
    <origin
        rpy="0 0 ${yaw}"
        xyz="${cos(yaw)*base_radius} ${sin(yaw)*base_radius} 0"
    />
    <parent link="base"/>
    <child link="upper_${number}"/>
</joint>

<transmission name="theta_${number}_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="theta_${number}">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="theta_${number}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
    </actuator>
</transmission>
</xacro:macro>

<xacro:joint_theta number="1" yaw="0"/>
<xacro:joint_theta number="2" yaw="${pi*2/3}"/>
<xacro:joint_theta number="3" yaw="${-pi*2/3}"/>


<!-- ===== LINKS ===== -->

<xacro:macro name="link_upper" params="number">
<link name="upper_${number}">
<xacro:cylinder_inertial
    mass="${upper_mass}"
    radius="${upper_radius}"
    length="${upper_length}"
    rpy="0 ${pi/2} 0"
/>
<visual>
    <geometry>
        <cylinder
            length="${upper_length}"
            radius="${upper_radius}"
        />
    </geometry>
    <origin
        xyz="${upper_length/2} 0 0"
        rpy="0 ${pi/2} 0"
    />
    <material name="upper"/>
</visual>
<collision>
    <geometry>
        <cylinder
            length="${upper_length}"
            radius="${upper_radius}"
        />
    </geometry>
    <origin
        xyz="${upper_length/2} 0 0"
        rpy="0 ${pi/2} 0"
    />
</collision>

<visual>
    <geometry>
        <cylinder
            length="${lower_width}"
            radius="${upper_radius}"
        />
    </geometry>
    <origin
        xyz="${upper_length} 0 0"
        rpy="${pi/2} 0 0"
    />
    <material name="upper"/>
</visual>
<collision>
    <geometry>
        <cylinder
            length="${lower_width}"
            radius="${upper_radius}"
        />
    </geometry>
    <origin
        xyz="${upper_length} 0 0"
        rpy="${pi/2} 0 0"
    />
</collision>
</link>
</xacro:macro>

<xacro:link_upper number="1"/>
<xacro:link_upper number="2"/>
<xacro:link_upper number="3"/>

<!-- ===== PARALLEL LINKAGE PARENT LINKS ===== -->

<xacro:macro name="parallel_parent" params="parent length child">
<joint name="${parent}_to_${child}_parent" type="fixed">
    <origin
        rpy="0 0 0"
        xyz="${length} 0 0"
    />
    <parent link="${parent}"/>
    <child link="${child}_parent"/>
</joint>
<link name="${child}_parent">
    <xacro:light_inertial/>
</link>
</xacro:macro>

<xacro:parallel_parent parent="upper_1" length="${upper_length}" child="lower_1"/>
<xacro:parallel_parent parent="upper_2" length="${upper_length}" child="lower_2"/>
<xacro:parallel_parent parent="upper_3" length="${upper_length}" child="lower_3"/>

</robot>
