<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="base">

<link name="world">
</link>
<joint name="world_to_base" type="fixed">
    <pose>
        0 0 ${upper_length + lower_length + 4*end_effector_depth}
        0 0 0
    </pose>
    <parent>world</parent>
    <child>base</child>
</joint>

<link name="base">
<inertial>
    <mass>${base_mass}</mass>
    <xacro:cylinder_inertia_sdf
        mass="${base_mass}"
        radius="${base_radius}"
        length="${base_depth}"
    />
</inertial>
<visual name="visual">
    <geometry>
        <cylinder>
            <length>${base_depth}</length>
            <radius>${base_radius}</radius>
        </cylinder>
    </geometry>
</visual>
<collision name="collision">
    <geometry>
        <cylinder>
            <length>${base_depth}</length>
            <radius>${base_radius}</radius>
        </cylinder>
    </geometry>
</collision>
</link>

</robot>
