theta_1_controller:
    type: effort_controllers/JointPositionController
    joint: theta_1
    pid: {p: 5.0, i: 1, d: 0.1}

theta_2_controller:
    type: effort_controllers/JointPositionController
    joint: theta_2
    pid: {p: 5.0, i: 1, d: 0.1}

theta_3_controller:
    type: effort_controllers/JointPositionController
    joint: theta_3
    pid: {p: 5.0, i: 1, d: 0.1}

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
