loops:
    - class: delta
      joints:
            theta_1: theta_1
            theta_2: theta_2
            theta_3: theta_3
            lower_1_alpha: lower_1_alpha
            lower_1_L_beta_top: lower_1_L_beta_top
            lower_1_L_gamma: lower_1_L_gamma
            lower_2_alpha: lower_2_alpha
            lower_2_L_beta_top: lower_2_L_beta_top
            lower_2_L_gamma: lower_2_L_gamma
            lower_3_alpha: lower_3_alpha
            lower_3_L_beta_top: lower_3_L_beta_top
            lower_3_L_gamma: lower_3_L_gamma

    - class: parallel
      joints:
          alpha: lower_1_alpha
          L_beta_top: lower_1_L_beta_top
          L_beta_bot: lower_1_L_beta_bot
          L_gamma: lower_1_L_gamma
          R_beta_top: lower_1_R_beta_top
          R_beta_bot: lower_1_R_beta_bot

    - class: parallel
      joints:
          alpha: lower_2_alpha
          L_beta_top: lower_2_L_beta_top
          L_beta_bot: lower_2_L_beta_bot
          L_gamma: lower_2_L_gamma
          R_beta_top: lower_2_R_beta_top
          R_beta_bot: lower_2_R_beta_bot

    - class: parallel
      joints:
          alpha: lower_3_alpha
          L_beta_top: lower_3_L_beta_top
          L_beta_bot: lower_3_L_beta_bot
          L_gamma: lower_3_L_gamma
          R_beta_top: lower_3_R_beta_top
          R_beta_bot: lower_3_R_beta_bot
