<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta">


<xacro:macro name="joints_lower" params="number">

<joint name="lower_${number}_L_ball_top" type="universal">
    <axis xyz="0 1 0"/>
    <axis2 xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="${upper_length} ${lower_width/2} 0"
    />
    <parent link="upper_${number}"/>
    <child link="lower_${number}_L_link"/>
</joint>

<!--
<joint name="lower_${number}_L_ball_bot" type="revolute2">
    <axis xyz="0 0 1"/>
    <axis2 xyz="0 1 0"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="${lower_length} 0 0"
    />
    <parent link="lower_${number}_L_link"/>
    <child link="lower_${number}_L_end"/>
</joint>
-->

<joint name="lower_${number}_R_ball_top" type="universal">
    <axis xyz="0 1 0"/>
    <axis2 xyz="0 0 1"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="${upper_length} ${-lower_width/2} 0"
    />
    <parent link="upper_${number}"/>
    <child link="lower_${number}_R_link"/>
</joint>

<!--
<joint name="lower_${number}_R_ball_bot" type="revolute2">
    <axis xyz="0 0 1"/>
    <axis2 xyz="0 1 0"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
    <origin
        rpy="0 0 0"
        xyz="${lower_length} 0 0"
    />
    <parent link="lower_${number}_R_link"/>
    <child link="lower_${number}_R_end"/>
</joint>
-->

<!-- Virtual links -->
<!--<link name="lower_${number}_L_end">
</link>
<link name="lower_${number}_R_end">
</link>-->
<!-- Should be fine so long as there is a fixed joint
to the end effector -->

</xacro:macro>

<xacro:joints_lower number="1"/>
<xacro:joints_lower number="2"/>
<xacro:joints_lower number="3"/>

</robot>
