<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delta_parameters">


<!-- ===== THETA ===== -->

<xacro:macro name="joint_theta" params="number yaw">
<joint name="theta_${number}" type="revolute">
    <axis><xyz>0 1 0</xyz></axis>
    <pose>
        0 0 ${yaw}
        ${cos(yaw)*base_radius} ${sin(yaw)*base_radius} 0
    </pose>
    <parent>base</parent>
    <child>upper_${number}</child>
</joint>
</xacro:macro>

<xacro:joint_theta number="1" yaw="0"/>
<xacro:joint_theta number="2" yaw="${pi*2/3}"/>
<xacro:joint_theta number="3" yaw="${-pi*2/3}"/>

</robot>
